version: '3.9'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - db
    command: air
  mysql:
    image: mysql
    restart: always
    container_name: go-mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'recordings'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - '33307:3306'
    networks:
      - db

networks:
  db:
    driver: bridge