version: '3.9'

services:
  app:
    container_name: gin-air-docker-crud-api
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    env_file:
      - .env
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    command: air
  mysql:
    image: mysql
    restart: always
    container_name: go-mysql-db
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - '33307:3306'
