version: '3.3'

services:
  go-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:33307'
    expose:
      - '3306'
    volumes:
      - my-go-db:/var/lib/mysql
volumes:
  my-go-db: