version: '3.9'

services:
  air:
    image: cosmtrek/air
    container_name: app
    working_dir: /app
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql
    restart: always
    container_name: go-mysql-db
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - '33307:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
