version: '3.9'

services:
  development:
    container_name: development
    image: cosmtrek/air
    working_dir: /app
    restart: always
    env_file:
      - .env.development
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql
    restart: always
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env.development
    volumes:
      - ./Docker/init:/docker-entrypoint-initdb.d
    ports:
      - '33307:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
