services:
  frontend-development:
    container_name: frontend-development
    image: node:20.11.1
    build: ./frontend
    ports:
      - "8000:8000"
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app
  backend-development:
    container_name: backend-development
    image: cosmtrek/air
    working_dir: /app/server
    restart: always
    env_file:
      - ./server/.env.development
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - /app/frontend # Exclude frontend from backend container
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.3.0
    restart: always
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./server/.env.development
    volumes:
      - ./server/Docker/init:/docker-entrypoint-initdb.d
    ports:
      - '33307:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
