version: '3.9'

services:
  air:
    image: cosmtrek/air
    container_name: app
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - .:/app
  mysql:
    image: mysql
    restart: always
    container_name: go-mysql-db
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - '33307:3306'
