version: '3.9'

services:
  mysql:
    image: mysql
    restart: always
    container_name: go-mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'recordings'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - '33307:3306'
